from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from complexity import estimate_complexity


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
OUTPUT_FILE = DOCS_DIR / "SOLUTIONS.md"
FOLDER_PATTERN = re.compile(r"^(?P<id>\d+)-(?P<slug>[a-z0-9-]+)$")

EXT_TO_LANGUAGE = {
    ".py": "Python",
    ".sql": "SQL",
    ".c": "C",
    ".cpp": "C++",
    ".cs": "C#",
    ".js": "JavaScript",
    ".java": "Java",
    ".ts": "TypeScript",
    ".kt": "Kotlin",
    ".go": "Go",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".swift": "Swift",
    ".php": "PHP",
    ".scala": "Scala",
    ".sh": "Bash",
}


@dataclass(frozen=True)
class ProblemRow:
    problem_id: int
    slug: str
    folder: str
    statement_count: int
    submission_count: int
    latest_submission: str
    languages: tuple[str, ...]
    time_complexity: str
    space_complexity: str


def collect_rows() -> list[ProblemRow]:
    rows: list[ProblemRow] = []
    for path in ROOT.iterdir():
        if not path.is_dir():
            continue

        match = FOLDER_PATTERN.match(path.name)
        if not match:
            continue

        problem_id = int(match.group("id"))
        slug = match.group("slug")

        statements = sorted(path.glob("*.md"))
        submissions = sorted(file for file in path.iterdir() if file.is_file() and file.suffix != ".md")

        languages = sorted(
            {
                EXT_TO_LANGUAGE.get(file.suffix.lower(), file.suffix.lower().lstrip(".").upper())
                for file in submissions
            }
        )
        latest_submission = submissions[-1].name if submissions else "-"
        if submissions:
            code = submissions[-1].read_text(encoding="utf-8", errors="ignore")
            time_complexity, space_complexity = estimate_complexity(code, submissions[-1].suffix)
        else:
            time_complexity, space_complexity = "N/A", "N/A"

        rows.append(
            ProblemRow(
                problem_id=problem_id,
                slug=slug,
                folder=path.name,
                statement_count=len(statements),
                submission_count=len(submissions),
                latest_submission=latest_submission,
                languages=tuple(languages),
                time_complexity=time_complexity,
                space_complexity=space_complexity,
            )
        )

    return sorted(rows, key=lambda row: row.problem_id)


def render_markdown(rows: list[ProblemRow]) -> str:
    language_counter: Counter[str] = Counter()
    total_submissions = 0

    for row in rows:
        language_counter.update(row.languages)
        total_submissions += row.submission_count

    lines: list[str] = []
    lines.append("# Solutions Index")
    lines.append("")
    lines.append("Auto-generated by `scripts/generate_index.py`.")
    lines.append("")
    lines.append("## Snapshot")
    lines.append("")
    lines.append(f"- Total problems: **{len(rows)}**")
    lines.append(f"- Total accepted submission files: **{total_submissions}**")
    lines.append("")
    lines.append("### Languages Used")
    lines.append("")
    if language_counter:
        for language, count in sorted(language_counter.items()):
            lines.append(f"- {language}: **{count}** problem folders")
    else:
        lines.append("- No submission files found.")
    lines.append("")
    lines.append("## Problem List")
    lines.append("")
    lines.append("| # | Problem | Submissions | Languages | Time (est.) | Space (est.) | Latest Submission |")
    lines.append("|---:|---|---:|---|---|---|---|")

    for row in rows:
        problem_name = row.slug.replace("-", " ").title()
        languages = ", ".join(row.languages) if row.languages else "-"
        lines.append(
            f"| {row.problem_id} | [{problem_name}](../{row.folder}) | "
            f"{row.submission_count} | {languages} | ~{row.time_complexity} | ~{row.space_complexity} | `{row.latest_submission}` |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows = collect_rows()
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(render_markdown(rows), encoding="utf-8")
    print(f"Updated {OUTPUT_FILE.relative_to(ROOT)} with {len(rows)} problems.")


if __name__ == "__main__":
    main()
